# Generated by Django 5.0.6 on 2024-05-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedImage',
            new_name='Image',
        ),
    ]
