# Generated by Django 5.0.6 on 2024-05-14 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_rename_uploadedimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('bounding_box', models.TextField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.image')),
            ],
        ),
    ]
